name: Publish

on:
  push:
    branches: [ master ]

jobs:
  generate-build-number:
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.buildnumber.outputs.build_number }}
    steps:
    - name: Generating
      id: buildnumber
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}
  publish:
    needs: [generate-build-number]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore --version-suffix ${{needs.generate-build-number.outputs.build_number}}
    - name: Publish Common
      uses: jankvr/publish-nuget@v0.9.0
      with:
          PROJECT_FILE_PATH: Common/Common.csproj
          VERSION_STATIC: 1.1.${{needs.generate-build-number.outputs.build_number}}
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish LogLibrary
      uses: jankvr/publish-nuget@v0.9.0
      with:
          PROJECT_FILE_PATH: LogLibrary/LogLibrary.csproj
          VERSION_STATIC: 1.1.${{needs.generate-build-number.outputs.build_number}}
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish CacheLibrary
      uses: jankvr/publish-nuget@v0.9.0
      with:
          PROJECT_FILE_PATH: CacheLibrary/CacheLibrary.csproj
          VERSION_STATIC: 1.1.${{needs.generate-build-number.outputs.build_number}}
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
    - name: Publish IdentityManagement
      uses: jankvr/publish-nuget@v0.9.0
      with:
          PROJECT_FILE_PATH: IdentityManagement/IdentityManagement.csproj
          VERSION_STATIC: 1.1.${{needs.generate-build-number.outputs.build_number}}
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish ProjectBase
      uses: jankvr/publish-nuget@v0.9.0
      with:
          PROJECT_FILE_PATH: ProjectBase/ProjectBase.csproj
          VERSION_STATIC: 1.1.${{needs.generate-build-number.outputs.build_number}}
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
