name: Publish

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate build number
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish Common
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: Common/Common.csproj
          VERSION_STATIC: 1.1.0.${{BUILD_NUMBER}}
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish LogLibrary
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: LogLibrary/LogLibrary.csproj
          VERSION_STATIC: 1.1.0.${{BUILD_NUMBER}}
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish CacheLibrary
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: CacheLibrary/CacheLibrary.csproj
          VERSION_STATIC: 1.1.0.${{BUILD_NUMBER}}
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish IdentityManagement
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: IdentityManagement/IdentityManagement.csproj
          VERSION_STATIC: 1.1.0.${{BUILD_NUMBER}}
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish ProjectBase
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: ProjectBase/ProjectBase.csproj
          VERSION_STATIC: 1.1.0.${{BUILD_NUMBER}}
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
